### ISSUE TITLE
Two Entity Managers

### ISSUE THREAD

**Issue by jeroendesloovere** [SimpleBus/DoctrineORMBridge#10]
Hi y'all.

## Problem description

I'm using CommandBus in my application and have noticed that only the `default` entityManager gets flushed. In this application I have a `custom` EntityManager that needs to get flushed too...

`default` EntityManger gets defined on the highest level, https://github.com/SimpleBus/DoctrineORMBridge/blob/master/src/MessageBus/WrapsMessageHandlingInTransaction.php

## Possible solutions?

Any suggestion how I can achieve this?
Many thanks.

**Comment by ruudk** [comment]
Maybe create your own `WrapsMessageHandlingInTransaction` middleware, and replace the existing one with this? :)

**Comment by cmodijk** [comment]
If you use the bridge without Symfony the solution is to have 2 instances of the `WrapsMessageHandlingInTransaction` class with the 2 different names in the constructor. If you use Symfony then we need to add support for defining multiple names in the configuration of the SymfonyBridge
* https://github.com/SimpleBus/SymfonyBridge/blob/master/src/DependencyInjection/DoctrineOrmBridgeConfiguration.php
* https://github.com/SimpleBus/SymfonyBridge/blob/master/src/Resources/config/doctrine_orm_bridge.yml#L2-L7

**Comment by cmodijk** [comment]
I'm closing this in favor of the new issue at the SymfonyBridge project
* https://github.com/SimpleBus/SymfonyBridge/issues/56
