### ISSUE TITLE
Wrapping event bus in a transaction

### ISSUE THREAD

**Issue by matiux** [SimpleBus/DoctrineORMBridge#11]
Hi,
can DoctrineORMBridge wrap an event bus in a transaction like the command bus?

it works with a command bus so I can save in dabatase with a transaction but when I handle an event `$this->eventBus->handle($event);` in the list of middleware I don't see the `WrapsMessageHandlingInTransaction` middleware

Thanks

**Comment by cmodijk** [comment]
The dision to not include this for the eventBus is that in principle the eventBus should not store or change any data it should only react to something and if something else needs to happen it in turn could trigger a other command.

**Comment by cmodijk** [comment]
@ruudk What is your opinion on this?

**Comment by cmodijk** [comment]
Yeah, it is bugging me to. How should we proceed?
