### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by Daredzik** [SimpleBus/DoctrineORMBridge#14]
According to this: https://github.com/SimpleBus/SymfonyBridge/issues/66 and this https://github.com/SimpleBus/SymfonyBridge/blob/master/src/DoctrineOrmBridgeBundle.php#L41

DoctrineORMBridge should have require:
`proxy-manager-bridge`

Coz after update packages composer prompt:
` In order to use bundle \"DoctrineOrmBridgeBundle\" you need to require \"symfo  ", "!!    ny/proxy-manager-bridge\" package.`

**Comment by ruudk** [comment]
Please report your issue here: https://github.com/SimpleBus/SimpleBus/issues
