### ISSUE TITLE
Add exception handling in WrapsMessageHandlingInTransaction middleware

### ISSUE THREAD

**Issue by jgoux** [SimpleBus/DoctrineORMBridge#2]
Hello,

If an exception is thrown in the EntityManager::transactional method, the entityManager becomes unusable for subsequent handlers.
A typical example is when you call the CommandBus in a loop.
We should inject the ManagerRegistry instead of the EntityManager to be able to get a new EntityManager in case of an exception.
We also need to add an option to specify a custom EntityManager. For example, we could inject the name of the EntityManager we want.
The handle method would look like : 
```php
public function handle(Message $message, callable $next)
    {
        $entityManager = $this->managerRegistry->getManager($this->entityManagerName);

        try {
            $entityManager->transactional(
                function () use ($message, $next) {
                    $next($message);
                }
            );
        } catch (Exception $e) {
            $this->managerRegistry->resetManager($this->entityManagerName);
            throw $e;
        }
    }
```

Edit : 
Following my example, if we decide to go this road, we'll have to always use the ManagerRegistry to get the EntityManager instead of directly injecting it. I can't find another (and proper) solution at the moment. :/

**Comment by matthiasnoback** [comment]
This has been fixed in 3.0.
