### ISSUE TITLE
Collecting events inside aggregate root

### ISSUE THREAD

**Issue by tomaszhanc** [SimpleBus/DoctrineORMBridge#3]
It's not a problem with a bridge itself, but how doctrine works. I've got an aggregate root which contains a collection. Inside a method where I'm adding a new item to that collection I raise an event that item was added but that event it's not collected. The reason is because the aggregate root is not mark as dirty - in fact, from the persistence, nothing changed inside that aggregate. Changes are made on added item (e.g. parent_id was set). Have you got any solution for that? Or only solution is to move event's recording to item instead of aggregate root.

**Comment by matthiasnoback** [comment]
Good question! This can be solved in several ways. You could have a "version" field on the parent entity which you'd increment/change whenever a change to one of the deeper-lying objects is made. This would then trigger the parent's domain events to be collected during the flush. This works best if the interaction with that deeper-lying object already happens through its "parent" entity. If that is not the case, you could try to use Doctrine bidirectional relations to navigate to the parent entity and record the domain event there.

**Comment by matthiasnoback** [comment]
I hope that helps :)

**Comment by tomaszhanc** [comment]
It's a good idea, next time I'll definitely try it. I solved this in a bit different way. I created DomainEventCollector service and call it's method on the end of every command. I know, it's not a perfect solution, but works for me (at least for now):

    final class DomainEventCollector
	{
		/** @var RecordsMessages */
		private $eventRecorder;

		public function __construct(RecordsMessages $eventRecorder)
		{
			$this->eventRecorder = $eventRecorder;
		}

		public function collectEvents(AggregateRoot $aggregateRoot)
		{
			foreach ($aggregateRoot->recordedMessages() as $event) {
				$this->eventRecorder->record($event);
			}

			$aggregateRoot->eraseMessages();
		}
	}

`AggreagteRoot` is implementing `ContainsRecordedMessages` interface.

**Comment by matthiasnoback** [comment]
Thanks for sharing the code. You might turn this class into a `ContainsRecordedMessages` itself and collect aggregate roots instead of events. Then you create a service definition for it and add the tag "event_recorder" to it.

**Comment by GeoffroyR** [comment]
I had same issue when calling methods on the aggregate root and recording messages without performing any change on the aggregate root itself.
I took another direction, why should we only collect events of the dirty entities?
So I changed the doctrine collector to check for all entities inside the UnitOfWork listening on the postFlush event:

```php
class CollectsEventsFromEntities implements EventSubscriber, ContainsRecordedMessages
{
    private $collectedEvents = array();

    public function getSubscribedEvents()
    {
        return array(
            Events::postFlush,
        );
    }

    public function postFlush(PostFlushEventArgs $args)
    {
        $uow = $args->getEntityManager()->getUnitOfWork();
        foreach ($uow->getIdentityMap() as $className => $entities) {
            foreach ($entities as $entity){
                $this->collectEventsFromEntity($entity);
            }
        }
    }

    public function recordedMessages()
    {
        return $this->collectedEvents;
    }

    public function eraseMessages()
    {
        $this->collectedEvents = array();
    }

    private function collectEventsFromEntity($entity)
    {
        if ($entity instanceof ContainsRecordedMessages) {
            foreach ($entity->recordedMessages() as $event) {
                $this->collectedEvents[] = $event;
            }
            $entity->eraseMessages();
        }
    }
}
```

If you want I can make a PR

**Comment by matthiasnoback** [comment]
I agree this is unexpected behavior: a command doesn't absolutely *need* to trigger a state change in the entity itself, but it might cause an event to be added, which you want to dispatch anyway.

I'll leave it to @cmodijk from here :)

**Comment by cmodijk** [comment]
@GeoffroyR I agree to if you can you make a PR for this?
