### ISSUE TITLE
Doctrine UoW execution order vs. no flush policy

### ISSUE THREAD

**Issue by Isinlor** [SimpleBus/DoctrineORMBridge#5]
Hello,

I have two questions.

The documentation states: 

> **Don't call flush() yourself**: Once you have added this middleware, you shouldn't call EntityManager::flush() manually from inside your command handlers anymore.

1. Why should I not do that? (I also can not find any failing case in the tests)
2. How to handle a case when I want to replace an entity with unique constraints with another entity that would violate the constraints? Doctrine Unit of Work execute inserts before deletes, therefore violating the constraints. The standard solution to such situation is to call `flush` after the delete and again after the persist, but the library is discouraging that.

Nice library btw 👍  .

**Comment by cmodijk** [comment]
> Why should I not do that? 

The reason behind this is that during the handeling of the command you are in a running transaction and if you flush in a handler and the handler fails after it is done then half of the work is done. This can lead to data that is incorrect. But it is a suggestion and you can still do this if you want to but you need to be carful when doing a flush in a command. 

> (I also can not find any failing case in the tests)

In my opinion this is a suggestion not a hard requirement

> How to handle a case when I want to replace an entity with unique constraints with another entity that would violate the constraints? Doctrine Unit of Work execute inserts before deletes, therefore violating the constraints. The standard solution to such situation is to call flush after the delete and again after the persist, but the library is discouraging that.

Yeah, this is the reason why I personally in rare cases flush inside a command handler I don't have a other solution for this.

**Comment by Isinlor** [comment]
Thanks for your explanation! :)

> The reason behind this is that during the handeling of the command you are in a running transaction and if you flush in a handler and the handler fails after it is done then half of the work is done

Not sure what you mean. If I fail in a transaction then the whole transaction is rolled back, at least when it comes to the SQL transactions. Moreover, a flush does not commit the transaction. Therefore flush should result only in SQL being executed and should not leave any corupted data if it fails.

Am I missing something?

**Comment by cmodijk** [comment]
> Not sure what you mean. If I fail in a transaction then the whole transaction is rolled back, at least when it comes to the SQL transactions. Moreover, a flush does not commit the transaction. Therefore flush should result only in SQL being executed and should not leave any corupted data if it fails.

You are right in this case;
* http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/transactions-and-concurrency.html

But the statement still stands as you shouldn't call EntityManager::flush() manually because the middleware takes care of that. But you can if you really need it :-)
